title: Maria Fernanda | Python Lover & PyLadie & Data Engineer
email: fsandrade25@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Maria Fernanda Souza Andrade | Python Lover & PyLadie & Data Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://naanadr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: naanadr
github_username:  naanadr
dev_to_username: naanadr
linkedin_username: naanadr
telegram_username: naanadr

# reading time
reading_time: true
words_per_minute: 200

#sidebar
default-image: channel-cover.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.


built-by: naanadr

copyright:
   name: naanadr
   link: 'https://naanadr.github.io'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 10
paginate_path: /page:num/


# Comments
disqus: yes
disqus-shortname: naanadr

# Include list
include: [assets/docs/maria_fernanda_souza_andrade_CV.pdf]

# Exclude list
exclude:
  - Gemfile
  - Gemfile.lock

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]
