title: Maria Fernanda | Python Lover & PyLadie & Data Engineer
email: fsandrade25@gmail.com
description: Maria Fernanda Souza Andrade | Python Lover & PyLadie & Data Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mfsouza.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: naanadr
github_username:  naanadr
dev_to_username: naanadr
linkedin_username: naanadr
telegram_username: naanadr

# reading time
reading_time: true
words_per_minute: 200

#sidebar
# default-image: channel-cover.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.


built-by: naanadr

copyright:
   name: naanadr
   link: 'https://mfsouza.com'

# Build settings
markdown: kramdown
paginate: 5
permalink: /blog/:title
paginate_path: /blog/page:num/

# Comments
disqus: yes
disqus-shortname: naanadr-github-io

# Tracker
analytics: UA-162706311-1

# Include list
include: [assets/docs/maria_fernanda_souza_andrade_CV.pdf]

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]
