title: Maria Fernanda | Python Lover & PyLadie & Data Engineer
description: > # this means to ignore newlines until "baseurl:"
  Maria Fernanda Souza Andrade | Python Lover & PyLadie & Data Engineer
baseurl: "" # the subpath of your site, e.g. /blog
email: mfsouza.contato@gmail.com
url: "https://mfsouza.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: naanadr
github_username:  naanadr
dev_to_username: naanadr
linkedin_username: naanadr
telegram_username: naanadr

# reading time
reading_time: true
words_per_minute: 200

built-by: naanadr

copyright:
   name: mfsouza
   link: 'https://mfsouza.com'

# Build settings
markdown: kramdown
paginate: 10
permalink: /blog/:title
paginate_path: /blog/page:num/

# Social
twitter:
  username: naanadr
  card: summary_large_image

# Comments
disqus: yes
disqus-shortname: mfsouza

# Tracker
analytics: UA-162706311-1

# Include list
include: [assets/docs/CV.pdf]

# Ruby Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
